name: Test on Arch Linux

on: [push]

jobs:
  test-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          ./a.sh
          apt --version

  test-on-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          ./a.sh
          brew --version

  test-on-arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm
          # Install required packages...
      - name: Run tests
        run: |
          ./a.sh
          pacman --version
