name: Test on Arch Linux

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  test-arch:
    runs-on: ubuntu-latest

    container:
      image: archlinux:base
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm
          # Install required packages...

      - name: Run tests
        run: |
          ./a.sh

